linter: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "lib/core/models/*.g.dart"
    - "lib/config/*.config.dart"
    - "lib/config/env.dart"
    - ".dart_tool/**"
    - "android/**"
    - "ios/**"
    - "build/**"
    - "images/**"
    - "assets/**"
    - "github/**"
