include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - conditional_uri_does_not_exist
    - directives_ordering
    - literal_only_boolean_expressions
    - prefer_asserts_with_message
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - throw_in_finally
    - unnecessary_await_in_return
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_colored_box
    - use_decorated_box
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - fvm/
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/config/env.dart
    - lib/generated_plugin_registrant.dart
    - test/**/**.mock.dart

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules:
    - arguments-ordering: false
    - avoid-late-keyword: false
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - no-equal-arguments:
        ignored-parameters:
          - height
          - width
          - spacing
          - padding
          - mainAxisSpacing
    - no-magic-number:
        allow-only-once: true
    - prefer-correct-identifier-length:
        exceptions: [ 'id' ]
        max-identifier-length: 30
        min-identifier-length: 3
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed
          - onTap
        allowed-line-count: 3
    - prefer-match-file-name:
        exclude:
          - lib/**/**_state.dart
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-static-class: false
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    
  metrics-exclude:
    - lib/**/*.config.dart
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.gform.dart
    - lib/generated_plugin_registrant.dart
    - test/**
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    lines-of-code: 100