name: tv_randshow
description: App to pick a random TV show episode

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.0
  cupertino_icons: ^0.1.2
  flutter_i18n: ^0.6.4
  http: ^0.12.0+2
  flutter_secure_storage: ^3.2.1+1
  meta: ^1.1.6
  sqflite: ^1.1.7+2
  scoped_model: ^1.0.1
  get_it: ^3.0.3
  cached_network_image: ^1.1.2+1

flutter:
  uses-material-design: true

  assets:
   - assets/i18n/
   - assets/img/no_image.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  