name: tv_randshow
description: App to pick a random TV show episode

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # Oficial Dart
  http: ^0.12.0+2                   # [Package] HTTP requests
  meta: ^1.1.7                      # [Package] Annotations for semantic information
  json_annotation: ^3.0.0           # [Package] Helpers to JSON code generation
  intl: ^0.15.8                     # [Package] Internationalized/localized messages and formatters
  # Oficial Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2           # [Package] Icons for iOS
  path_provider: ^1.4.0             # [Plugin] Locations on the Android & iOS file systems
  flutter_secure_storage: ^3.2.1+1  # [Plugin] Store data in secure storage
  # Others
  get_it: ^3.0.3                    # [Package] Service locator
  scoped_model: ^1.0.1              # [Package] Scoped model architecture
  flutter_i18n: ^0.6.4              # [Package] Internationalization strings
  cached_network_image: ^1.1.2+1    # [Package] Load and cached network images
  sqflite: ^1.1.7+2                 # [Plugin] SQLite

dev_dependencies:
  build_runner: ^1.0.0              # [Package] Command line JSON conde generation
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true

  assets:
   - assets/i18n/
   - assets/img/no_image.png
  fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/nunito-regular.ttf
      - asset: assets/fonts/nunito-bold.ttf
      - asset: assets/fonts/nunito-semibold.ttf
  - family:  Unicons
    fonts:
      - asset: assets/fonts/unicons.ttf
  