name: tv_randshow
description: App to pick a random TV show episode

version: 1.1.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # Official Dart
  json_annotation: ^3.0.0           # [Package] Helpers to JSON code generation
  # Official Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^5.4.5              # [Plugin] For launching a URL in mobile platforms
  url_launcher_web: ^0.1.1+2        # [Plugin] For launching a URL in web platform
  path_provider: ^1.6.5             # [Plugin] Locations on the Android & iOS file systems
  # Others
  provider: ^4.0.4                  # [Package] State management
  get_it: ^4.0.2                    # [Package] Dependency injection
  injectable: ^0.4.0+1              # [Package] Code generator dependency injection
  flutter_translate: ^1.6.0         # [Package] I18n translate
  cached_network_image: ^2.0.0      # [Package] Load and cached network images
  flutter_pagewise: ^1.2.3          # [Package] List pagination
  flare_flutter: ^2.0.4             # [Package] Runtime flare animation
  logger: ^0.8.0                    # [Package] Logger for debug
  dio: ^3.0.9                       # [Package] HTTP Client manager
  launch_review: ^2.0.0             # [Package] Open store to rate app
  flutter_markdown: ^0.4.1          # [Package] Markdown support
  sqflite: ^1.2.2                   # [Plugin] SQLite
  persist_theme: ^1.7.0             # [Plugin] Manage and persist theme
  stacked: ^1.7.4                   # [Package] Architecture package

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0              # Command line JSON code generation
  json_serializable: ^3.2.0         # Json serializable generator
  flutter_native_splash: ^0.1.9     # Splash screen native generator 
  flutter_launcher_icons: ^0.7.4    # Launcher icons native generator
  injectable_generator: ^0.4.1      # DI code generator
  mockito: ^4.1.1                   # Mock data generator

flutter_native_splash:
  image: assets/img/icon_launcher.png
  color: "E40505"
  
flutter_icons:
  android: "ic_launcher" 
  adaptive_icon_foreground: "assets/img/icon_launcher_foreground.png"
  adaptive_icon_background: "#E40505"
  ios: false
  image_path: "assets/img/icon_launcher.png"
  
flutter:
  assets:
    - assets/i18n/
    - assets/markdown/
    - assets/img/no_image.webp
    - assets/img/loading.flr
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito-regular.ttf
    - family:  Unicons
      fonts:
        - asset: assets/fonts/unicons.ttf