name: Integration test
on:
  push:
    branches:
      - "main"
      - "develop"
jobs:
  android-integration-test:
    name: run integration test on Android emulator
    runs-on: macos-latest
    steps:
      - name: configure enviroment
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - name: code analyze
        run: flutter analyze
      - name: unit tests
        run: flutter test --dart-define=API_KEY=${{ secrets.API_KEY_TMDB }}
      - name: integration tests
        timeout-minutes: 30
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: pixel_3a
          arch: x86
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            flutter pub get
            flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --flavor dev --dart-define=API_KEY=${{ secrets.API_KEY_TMDB }}
