name: Release APK
on:
  push:
    branches:    
      - master
    tags:        
      - v*
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.5'
    # Get Dart VM SDK
    - run: sudo apt-get update
    - run: sudo apt-get install apt-transport-https
    - run: sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    - run: sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
    - run: sudo apt-get update
    - run: sudo apt-get install dart
    # Generate env.dart with Dart SDK
    - env: 
        API_KEY_TMDB: ${{ secrets.API_KEY_TMDB }}
    - run: dart .tool/env.dart
    - run: flutter analyze
    - run: flutter pub get
    - run: flutter build apk --flavor prod -t lib/main_prod.dart
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN_REPO }}
        
