name: Test 
on: 
  push:
    branches:
      - master
      - develop
jobs: 
  build-and-test: 
    name: run analyze code and build test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: dart .tool/env.dart
      env:
        API_KEY_TMDB: ${{ secrets.API_KEY_TMDB }}
    - run: flutter test
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter build aot -t lib/main_dev.dart
  android-integration-test:
    name: run integration test on Android emulator
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - "pixel"
          - "pixel_c"
          - "Nexus 6P"
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: dart .tool/env.dart
        env:
          API_KEY_TMDB: ${{ secrets.API_KEY_TMDB }}
      - run: flutter test
      - name: run tests
        timeout-minutes: 30
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: ${{ matrix.device }}
          script: |
            /Users/runner/Library/Android/sdk/tools/bin/avdmanager list
            flutter pub get
            flutter drive --target=test_driver/app.dart --flavor dev
